source "https://rubygems.org"

ruby "~> 4.0"

gem "aws-sdk-s3", "~> 1"
gem "aws-sdk-sesv2", "~> 1"
gem "bcrypt", "~> 3.1"
gem "csv", "~> 3.3"
gem "dotenv", "~> 3.1"
gem "exifr", "~> 1.4"
gem "ffi-geos", "~> 2.5"
gem "mcp", "~> 1.1"
gem "ruby-vips", "~> 2.2"
gem "pg", "~> 1.5"
gem "premailer", "~> 1.29"
gem "puma", "~> 6.6"
gem "que", "~> 2.4"
gem "rake", "~> 13.2"
gem "redcarpet", "~> 3.6"
gem "rgeo", "~> 3.0"
gem "roda", "~> 3.102"
gem "rodauth", "~> 2.43"
gem "rodauth-oauth", "~> 1.6"
gem "rubyzip", "~> 2.4"
gem "sanitize", "~> 7.0"
gem "sequel", "~> 5.103"
gem "tilt", "~> 2.6"
gem "tzinfo", "~> 2.0"

group :development, :test do
  gem "rack-test", "~> 2.1"
  gem "rspec", "~> 3.13"
  gem "sqlite3", "~> 2.0"
  gem "standard", "~> 1.43"
end
